<?php

namespace AppBundle\Repository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForUserOrderedByLastMessageDesc($userId)
    {
        return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('c')
        ->from('AppBundle:Conversation', 'c')
        ->where(':user_id MEMBER OF c.members')
        ->orderBy('c.lastMessageAt', 'DESC')
        ->setParameter('user_id', $userId)
        ->getQuery()
        ->getResult();
    }
}
