<?php

namespace AppBundle\Repository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForUserOrderedByLastMessageDesc($userId)
    {
        return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('c')
        ->from('AppBundle:Conversation', 'c')
        ->where('c.id in (SELECT IDENTITY(m.conversation) FROM AppBundle:ConversationMember m WHERE m.user = :user_id)')
        ->orderBy('c.lastMessageAt', 'DESC')
        ->setParameter('user_id', $userId)
        ->getQuery()
        ->getResult();
    }
}
