<?php

namespace AppBundle\Repository;

/**
 * StoreTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
