<?php

namespace AppBundle\Repository;

/**
 * TakenPickupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TakenPickupRepository extends \Doctrine\ORM\EntityRepository
{
}
