<?php

namespace AppBundle\Repository;

/**
 * TakenPickupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TakenPickupRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNextForUserOrderedByDate($userId)
    {
        return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('p')
        ->from('AppBundle:TakenPickup', 'p')
        ->where(':user_id = p.user')
        ->andWhere('p.at > :min_date')
        ->orderBy('p.at', 'ASC')
        ->setParameter('user_id', $userId)
        ->setParameter('min_date', new \DateTime('-1 hour'))
        ->getQuery()
        ->getResult();
    }
}
