# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.salted_md5_encoder:
        class: AppBundle\Security\SaltedMD5Encoder

    app.foodsharing_authenticator:
        class: AppBundle\Security\FoodsharingAuthenticator
        arguments: ['@logger', '@serializer']

    app.logout_success_handler:
        class: AppBundle\Security\LogoutSuccessHandler

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
